### ISSUE TITLE
withMemoryRebound

### ISSUE THREAD

**Issue by serges147** [daisuke-t-jp/Mach-Swift#3]
@daisuke-t-jp I believe there are bugs in code like following (for example for the `Mach.Host.Statistics. cpuLoadInfo`):
```
$0.withMemoryRebound(to: integer_t.self, capacity: Int(count)) { ... }
```
The `capacity` should be 1 b/c it was pointer to one instance of `host_cpu_load_info`.

**Comment by daisuke-t-jp** [comment]
Hi @serges147

`withMemoryRebound()` binds to `integer_t` type  and specifies the count(`capacity`) of `integer_t`.

The `count` of `integer_t` is calculated based on `host_cpu_load_info`.

```swift
var count = mach_msg_type_number_t (MemoryLayout <host_cpu_load_info> .stride / MemoryLayout <integer_t> .stride)
```

So I think there is no problem.

Thanks.

**Comment by serges147** [comment]
Yes, I’ve got your logic, but I believe you misunderstood the capacity parameter - it is not about number of integer_t-s, but instead number of items of original pointer (which is one `host_cpu_load_info` item).

**Comment by daisuke-t-jp** [comment]
Hi @serges147

Thank you for your help.

I was misunderstanding this method.

https://developer.apple.com/documentation/swift/unsafepointer/2430863-withmemoryrebound

> count
> The number of instances of Pointee to bind to type.

I fixed mismatch. https://github.com/daisuke-t-jp/Mach-Swift/commit/4351198af8b35c99babf350ea154a07d458798eb

Thanks a lot.

**Comment by serges147** [comment]
You welcome!
